### ISSUE TITLE
Setup TravisCI Tests to Run on Python 2.7.x

### ISSUE THREAD

**Issue by bbugyi200** [bbugyi200/funky#136]
Currently only Python versions 3.4, 3.5, and 3.6 are tested. Before 2.7.x can be added to CI, however, the unit tests need to be fixed for compatibility with Python 2.7.x.

**Comment by ArthurCueio** [comment]
Hey, Do you just want the tests to run on a Python 2.7 environment or something else?

**Comment by bbugyi200** [comment]
@ArthurCueio I want the tests to run on Python versions 2.7, 3.4, 3.5, and 3.7. (They currently only run on versions 3.4, 3.5 and 3.6.)

I added Python 2.7.X support in response to #127 and would like to make sure that I don't inadvertently break compatibility in the future.

**Comment by ArthurCueio** [comment]
Ok, that should be pretty straight forward, I'll try to implement it.
