### ISSUE TITLE
Output location of funky.sh on install

### ISSUE THREAD

**Issue by unikitty37** [bbugyi200/funky#163]
The README says that `funky.sh` will be installed to `~/.local/share/funky/funky.sh`, or `/usr/share/funky/funky.sh` if installed as root. However, it has not been installed to either of these locations.

`find ~ -name funky.sh` did not find anything; I eventually found it under `/usr/local/lib/python3.8/site-packages/scripts/shell/funky.sh`. `$XDG_DATA_HOME` is not set, but while a Python dev might have that set, or know to look in that location, it's not very intuitive for those of us who aren't Python devs :)

It would be very helpful if the installation process could output the location where this file has been installed, though I don't know if pip allows for that.

In the meantime, is it worth mentioning this other possible location in the README?

(Obviously, #99 would make this redundant…)

```
└─▷ pip3 install pyfunky
Collecting pyfunky
  Downloading pyfunky-3.4.0.tar.gz (22 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 10.4 MB/s
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Requirement already satisfied: six in /usr/local/Cellar/protobuf/3.12.2/libexec/lib/python3.8/site-packages (from pyfunky) (1.14.0)
Building wheels for collected packages: pyfunky, future
  Building wheel for pyfunky (setup.py) ... done
  Created wheel for pyfunky: filename=pyfunky-3.4.0-py2.py3-none-any.whl size=18312 sha256=0f32f50028db9572b5a50bd3adccfce0968b070a29705421bd6398e35066a80b
  Stored in directory: /Users/unikitty/Library/Caches/pip/wheels/b5/ad/9a/e04b823f26b5fae9476898b4fbf0073579edfa5854a8cd79cd
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=59ed74961449bc9675a776a3be2c700c155c655e2b24498e8dbc27d5dd59bd3a
  Stored in directory: /Users/unikitty/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built pyfunky future
Installing collected packages: future, pygments, pyfunky
Successfully installed future-0.18.2 pyfunky-3.4.0 pygments-2.6.1
```

**Comment by agbell** [comment]
+1 
hitting the same problem. Great tool though

**Comment by agbell** [comment]
Actually even better would be to have funky emit the shell script when given a specific option. so
``` 
source $(funky init)
```
would work

**Comment by bbugyi200** [comment]
From [v3.5.0] onward, you can add the following line to your `.bashrc` / `.zshrc` file to hook funky into your shell, so there is no longer any need to locate the `funky.sh` file:

```shell
eval "$(funky --init SHELL)"  # where SHELL is either 'bash' or 'zsh'
```

Alternatively, you can run `funky --setup-shell SHELL` to have funky add this line for you.

[v3.5.0]: https://github.com/bbugyi200/funky/blob/master/CHANGELOG.md#v350-2021-08-21
