### ISSUE TITLE
Local funks are being run when in different folder, or after deletion

### ISSUE THREAD

**Issue by unikitty37** [bbugyi200/funky#164]
When I define a local funk in a folder, my understanding is that that funk will only run when I am in that folder.

However, they seem to persist.

```
$ mkdir test
$ cd test
$ funky -a yarn

IGNORED="$@"
echo "You ran yarn"

$ yarn --help
```

Output is "You ran yarn", as expected.

```
$ cd ..
$ yarn --help

```

Output is "You ran yarn", and not the Yarn help.

```
$ cd test
$ funky -r yarn
$ yarn --help
```

Output is "You ran yarn", and not the Yarn help. `which yarn` shows the function is still defined.

I'm running zsh 5.8 on macOS 10.14.6, and I have sourced `funky.sh` in my `.zshrc` and run `exec zsh` to force it to be loaded.

Does anybody know what's going on here?

**Comment by french-frie** [comment]
Hey @unikitty37 , i don't know if your still searching for a solution here but i ended up modifying their `funky.sh` script.

Props to those guys to have done this tool, it does what it is supposed to do but realised that it wasn't exactly what i expected:
- It wasn't unsetting the aliases when leaving a directory with funks
- If you had a terminal open with funks, opening up another one would load the funks from the other one

It probably isn't the prettiest script ever made, but it's honest work.

I wanted to submit a pull request, but setting up the dev environment didn't work for me. I am really not used to python, but I'll try to set that up properly and submit a proper pull request with tests etc... when i have more time.

The modified script enables you to load as many funks per terminal as you wish, without influencing the others and unset properly everything when leaving folder containing the funks for that terminal.

You can find the modified script here: https://gist.github.com/french-frie/e2dba185419f69f22a6835cf4cbe4aca

Feel free to modify it as you wish, i have tested it as much as i could and it's running smoothly on my machine and absolutely love it.

@bbugyi200 Feel free to take the script and run it through a bunch of tests and release a version if you feel it is worth it or if my PR don't come.

Cheers

**Comment by unikitty37** [comment]
Thanks — I ended up using [smartcd](https://github.com/cxreg/smartcd) instead, as I was able to get that working the way I wanted.

**Comment by bbugyi200** [comment]
@unikitty37 Hmm. I've never heard of smartcd before. I've added it to the [Similar Projects](https://github.com/bbugyi200/funky#similar-projects) section of funky's README.

@french-frie Thanks for the contribution! I think it's working well in #165. I'm going to dog-food this PR for a few weeks before merging.
