### ISSUE TITLE
Add `funky --init SHELL` command

### ISSUE THREAD

**Issue by bbugyi200** [bbugyi200/funky#166]
Actually even better would be to have funky emit the shell script when given a specific option. so
``` 
source $(funky init)
```
would work

_Originally posted by @agbell in https://github.com/bbugyi200/funky/issues/163#issuecomment-883642118_

**Comment by bbugyi200** [comment]
The final solution looks like it is going to be to place the following line in your .bashrc / .zshrc file: `eval "$(funky --init)"`

**Comment by adamgordonbell** [comment]
Great work!
