### ISSUE TITLE
json decoder error

### ISSUE THREAD

**Issue by nicoandmee** [bbugyi200/funky#174]
I found this project from https://earthly.dev/blog/command-line-tools/. I'm using the `.funky` file example given there (also below):
```
lint() { markdownlint --fix "./_posts/*.md"; }
set-header() { cp "$(latest-image)" "$(image-folder)/header.jpg"; }
set-image() { cp "$(latest-image)" "$(image-folder)/$(date +%s).png"; }
``` 
But when I run `funky` in the same directory as my `.funky` I get: [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0). What's going on here? Am I maybe getting the format of my `.funky` completely wrong? Any help is greatly appreciated!

**Comment by bbugyi200** [comment]
@nicoandmee Thanks for trying out the project. The .funky file is created by `funky`; you should not manually edit this file. After [Installing funky](https://github.com/bbugyi200/funky#installation), you should be able to run `funky -a foobar` to add a new local funk to the current directory.
