### ISSUE TITLE
How can I backup my defined functions

### ISSUE THREAD

**Issue by larsrinn** [bbugyi200/funky#187]
Hi,

first of all let me thank you for that project. I makes my life easier almost every day :)  Now, I would like to backup my functions/move to a new machine. How can I do that?

**Comment by bbugyi200** [comment]
@larsrinn Thanks for creating an issue. I'm glad you find funky useful!

Currently, all local funks are stored in a JSON file named `.funky` inside the directory the funks are associated with. So backing up your funks is just a matter of copying those `.funky` files to the desired directories on your new machine.

This is far from ideal, I know. I am considering migrating funks to a global sqlite database (see https://github.com/bbugyi200/funky/issues/124), which would be an improvement I think.

**Comment by bbugyi200** [comment]
I'm going to close this issue, since I believe I have answered your question, but feel free to re-open if you disagree.
